version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_DB: dev
      POSTGRES_HOST_AUTH_METHOD: trust   # passwordless
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  valkey:
    image: valkey/valkey:7-alpine
    container_name: valkey
    command: ["valkey-server", "--appendonly", "no"]  # no password
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

volumes:
  postgres_data:
